### ISSUE TITLE
Make it work on Python 2.7

### ISSUE THREAD

**Issue by lvh** [latacora/pikara#7]
Currently this is failing because the tests create pickles with protocol version 3 and Python 2.7 only supports v2.

When this is done, remove the Travis allowed failure for Python 2.7.

**Comment by moreati** [comment]
Would [zodbpickle](https://pypi.org/project/zodbpickle/) be an acceptable dependency to gain Pickle 3 superpowers on Python 2?
> Under Python2, this package forks both Python 2.7’s pickle and cPickle modules, adding support for the protocol 3 opcodes

**Comment by moreati** [comment]
This won't be as simple as I thought. zodbpickle doesn't port pickletools from Python 3.x to Python 2.x, it just includes it as `zodbpickle.pickletools_3`. So you get an ImportError

```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zodbpickle.pickletools_3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/src/pikara/.tox/py27/local/lib/python2.7/site-packages/zodbpickle/pickletools_3.py", line 2049
    print("%5d:" % pos, end=' ', file=out)
                           ^
SyntaxError: invalid syntax
```

**Comment by lvh** [comment]
FWIW: I'm not sure if you took a look at how pikara works right now, but it's a virtual pickle VM. If Python 3 produces the high-version pickle, Python 2 should be able to consume it. Right now the tests don't do that because they consist of both a dumps and a parse, but there's no reason (some of) the tests couldn't be a parse with a saved pickle.

**Comment by moreati** [comment]
Ah, thank you. I hadn't realised the `pickle.dumps()` were an implementation detail of the test suite.
